image:
  file: .gitpod.Dockerfile

workspaceLocation: 'project'
checkoutLocation: 'project'

# Commands to start on workspace startup
tasks:
  - before: |
      sudo cp /workspace/project/freeCodeCamp/.bashrc ~/.bashrc
      exit

vscode:
  extensions:
    - CodeRoad.coderoad
